import { createContext, useContext, useState, type ReactNode } from "react";

export type Locale = "fr" | "it" | "de" | "en" | "rm";

export const SUPPORTED_LOCALES: { code: Locale; label: string }[] = [
  { code: "fr", label: "FR" },
  { code: "it", label: "IT" },
  { code: "de", label: "DE" },
  { code: "en", label: "EN" },
  { code: "rm", label: "RM" },
];

const translations: Record<Locale, Record<string, string>> = {
  fr: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Transformez votre documentation interne en formations intelligentes",
    select_role: "Choisissez votre profil",
    rbac: "RBAC – Contrôle d'accès basé sur les rôles",
    admin_title: "Administrateur",
    admin_desc: "Créez des formations, définissez les sources, gérez les accès",
    user_title: "Collaborateur",
    user_desc: "Suivez vos formations, personnalisez vos objectifs, jeux de rôle",
    invite_title: "Inviter un participant",
    invite_desc: "Générer un lien d'invitation",
    invite_copy: "Copier le lien",
    invite_copied: "Lien copié !",
    invite_email_placeholder: "email@exemple.com",
    invite_send: "Envoyer l'invitation",
    enter: "Accéder",
    feat_ai: "Génération IA",
    feat_rag: "Moteur RAG",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Hébergement Suisse",
    arch_title: "Architecture Client / Serveur",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite exécuté dans le navigateur de l'utilisateur. Interface d'interaction avec l'IA.",
    arch_server: "Serveur (Backend)",
    arch_server_desc: "Hébergé chez Infomaniak (Suisse), Ubuntu Server, API sécurisée, moteur RAG.",
    footer: "Conçu en Suisse",
    login_title: "Connexion",
    login_email: "Adresse e-mail",
    login_password: "Mot de passe",
    login_submit: "Se connecter",
    login_back: "Retour à l'accueil",
    login_error: "Échec de connexion",
    login_error_desc: "Email ou mot de passe incorrect",
    login_test_mode: "Mode test — authentification locale (JSON)",
    access_restricted: "Accès réservé aux membres",
    download: "Télécharger",
    // Sidebar
    nav_dashboard: "Tableau de bord",
    nav_formations: "Formations",
    nav_documents: "Documents",
    nav_create_course: "Générateur de Cours",
    nav_evaluations: "Évaluations",
    nav_roleplay: "Jeu de rôle",
    nav_analytics: "Analytics",
    nav_users: "Utilisateurs",
    nav_settings: "Paramètres",
    nav_invite: "Inviter",
    role_guest: "invité",
    nav_logout: "Déconnexion",
    // Dashboard
    dashboard_title: "Tableau de bord",
    dashboard_subtitle: "Vue d'ensemble de votre Knowledge Engine",
    dashboard_subtitle_guest: "Vos formations et évaluations",
    stat_active_learners: "Apprenants actifs",
    stat_active_formations: "Formations actives",
    stat_indexed_docs: "Documents indexés",
    stat_avg_score: "Score moyen",
    stat_change_month: "+12% ce mois",
    stat_change_week: "+3 cette semaine",
    stat_new_docs: "82 nouveaux",
    stat_vs_last_month: "+5% vs mois dernier",
    stat_assigned: "assignées",
    formations_in_progress: "Formations en cours",
    active: "actives",
    modules: "modules",
    recent_activity: "Activité récente",
    quick_generate: "Générer une formation",
    quick_generate_desc: "À partir de vos documents",
    quick_analytics: "Voir les analytics",
    quick_analytics_desc: "Performance des équipes",
    quick_roleplay: "Lancer un jeu de rôle",
    quick_roleplay_desc: "Simulation interactive",
    quick_invite: "Inviter un participant",
    quick_invite_desc: "Lien d'invitation externe",
    // Documents
    docs_title: "Documents",
    docs_subtitle: "Bibliothèque documentaire & base vectorielle",
    docs_import: "Importer",
    docs_search: "Rechercher un document...",
    docs_filter: "Filtrer",
    docs_drop_zone: "Glissez vos fichiers ici ou cliquez pour importer",
    docs_drop_subtitle: "PDF, DOCX, TXT — Max 20MB par fichier",
    docs_generate_training: "Générer une formation",
    docs_generate_desc: "Décrivez la formation à créer à partir de vos documents importés",
    docs_chat_placeholder: "Ex : Créer une formation sécurité réseau à partir des documents IT...",
    col_document: "Document",
    col_service: "Service",
    col_size: "Taille",
    col_chunks: "Chunks",
    col_status: "Statut",
    col_date: "Date",
    col_actions: "Actions",
    status_indexed: "Indexé",
    status_pending: "En cours",
    pii_anonymized: "🛡️ Données anonymisées",
    pii_replaced: "PII remplacées",
    // Formations
    formations_title: "Formations",
    formations_subtitle: "Parcours générés automatiquement par l'IA",
    formations_generate: "Générer une formation",
    formations_readonly: "Lecture seule",
    formations_admin_only: "Réservé aux admins",
    status_active: "Active",
    status_draft: "Brouillon",
    participants: "participants",
    // Evaluations
    eval_title: "Évaluations",
    eval_next: "Suivant",
    eval_finish: "Terminer",
    eval_restart: "Recommencer",
    eval_success: "Excellent ! Vous maîtrisez ce module.",
    eval_fail: "Des axes d'amélioration ont été identifiés.",
    eval_correct: "Correct",
    eval_incorrect: "Incorrect",
    eval_question: "Question",
    // Roleplay
    roleplay_title: "Jeu de rôle",
    roleplay_subtitle: "Simulation interactive basée sur vos procédures internes",
    roleplay_placeholder: "Votre action ou réponse...",
    // Analytics
    analytics_title: "Analytics",
    analytics_subtitle: "Performance et suivi des compétences",
    analytics_completion_rate: "Taux de complétion",
    analytics_avg_time: "Temps moyen",
    analytics_active_users: "Utilisateurs actifs",
    analytics_global_progress: "Progression globale",
    analytics_service_perf: "Performance par service",
    analytics_skills_map: "Cartographie des compétences",
    analytics_skills_desc: "Détection automatique des lacunes par service",
    analytics_completion: "Complétion",
    analytics_avg_score: "score moy.",
    analytics_active: "actifs",
    // AI Prompt
    nav_ai_prompt: "Prompt IA",
    ai_title: "Prompt IA",
    ai_subtitle: "Sélectionnez vos documents et décrivez ce que vous attendez de l'IA",
    ai_select_docs: "Documents disponibles",
    ai_select_all: "Tout sélectionner",
    ai_deselect_all: "Tout désélectionner",
    ai_no_docs_yet: "Aucun document disponible. Importez des fichiers depuis la page Documents.",
    ai_clean: "Aucun PII",
    ai_prompt_label: "Votre instruction",
    ai_prompt_placeholder: "Ex : Résumez les points clés de ces documents en 5 bullet points...",
    ai_docs_selected: "{n} document(s) sélectionné(s)",
    ai_docs_none_selected: "Aucun document sélectionné",
    ai_send: "Envoyer",
    ai_no_docs_title: "Aucun document",
    ai_no_docs_desc: "Veuillez sélectionner au moins un document",
    ai_no_prompt_title: "Prompt vide",
    ai_no_prompt_desc: "Veuillez décrire ce que vous attendez de l'IA",
    ai_sent_title: "Prompt envoyé",
    ai_sent_desc: "Votre demande a été transmise avec les documents sélectionnés",
    score: "Score",
    // New keys
    person: "Personne",
    organization: "Organisation",
    location: "Lieu",
    misc: "Divers",
    email: "Email",
    phone: "Téléphone",
    iban: "IBAN",
    social_security: "N° Sécu",
    avs: "N° AVS",
    date: "Date",
    amount: "Montant",
    address: "Adresse",
    url: "URL",
    ip_address: "Adresse IP",
    siret_siren: "SIRET/SIREN",
    cni: "CNI",
    urssaf: "URSSAF",
    mutuelle: "Mutuelle",
    reference: "Référence",
    zip_code: "Code postal",
    ide: "IDE",
    birth_date: "Date naissance",
    cancel: "Annuler",
    confirm: "Confirmer",
    close: "Fermer",
    preview: "Prévisualiser",
    delete: "Supprimer",
    loading: "Chargement...",
    docs_extracting: "Extraction du texte en cours...",
    docs_analyzed: "Documents analysés",
    docs_status_pii: "Statut PII",
    docs_categories: "Catégories",
    docs_date: "Date",
    docs_actions: "Actions",
    docs_scanning_label: "Analyse...",
    docs_no_pii: "Aucun PII",
    docs_pii_count: "{n} PII",
    docs_rag_indexing: "indexation RAG...",
    docs_rag_indexed: "indexé RAG",
    docs_rag_failed: "échec indexation",
    docs_empty_state: "Aucun document analysé. Importez un fichier pour lancer la détection PII.",
    docs_saving_server: "Envoi au serveur",
    docs_saving_desc: "Transfert sécurisé du document en cours...",
    docs_save_success: "Analyse et transfert terminés",
    docs_save_success_desc: "{n} donnée(s) sensible(s) détectée(s) et document importé au système RAG",
    docs_ready_for_ai: "Le document est prêt pour l'IA",
    docs_server_error: "Erreur serveur",
    docs_server_error_desc: "Le document n'a pas pu être envoyé au RAG.",
    docs_preview_pii_replaced: "donnée(s) sensible(s) remplacée(s) par des tokens",
    docs_preview_no_pii: "Aucune donnée sensible détectée",
    docs_export_tokenized: "Exporter tokenise",
    pii_analysis_title: "Analyse PII",
    pii_analysis_desc: "Analyse de « {name} » avant envoi",
    pii_verification_desc: "Vérification des données sensibles avant traitement",
    pii_loading_model: "Chargement du modèle NER…",
    pii_entities_detected: "{n} donnée(s) sensible(s) détectée(s)",
    pii_no_entities: "Aucune donnée sensible détectée ✓",
    pii_hide_originals: "Masquer les originaux",
    pii_view_originals: "Voir les originaux",
    pii_send_anonymized: "Envoyer anonymisé",
    pii_send_anyway: "Envoyer",
    ai_generation_error: "Erreur de génération",
    ai_generation_fail_desc: "Impossible de générer une réponse.",
    ai_answer_title: "Réponse",
    ai_sources_used: "Sources utilisées",
    dash_current_role: "Rôle actuel",
    dash_admin_role: "Administrateur",
    dash_user_role: "Utilisateur",
    dash_quick_upload_desc: "Uploader et analyser des documents avec détection PII",
    dash_system_status: "État du Système",
    dash_tool_pii: "Moteur PII",
    dash_tool_rag: "Base RAG",
    dash_tool_courses: "Générateur",
    dash_status_active: "Actif",
    dash_status_ready: "Prêt",
    dash_status_online: "En ligne",
    // Course Generation
    course_gen_title: "Générateur de Cours IA",
    course_gen_subtitle: "Créez un parcours d'apprentissage personnalisé à partir de vos documents.",
    course_gen_demo_btn: "Essayer le Mode Démo",
    course_gen_setup_title: "Configuration du Cours",
    course_gen_setup_desc: "Définissez le sujet et vos objectifs pour une expérience sur mesure.",
    course_gen_topic_label: "Sujet du cours",
    course_gen_topic_placeholder: "ex: Intelligence Artificielle, Cuisine Italienne...",
    course_gen_goal_label: "Objectif d'apprentissage",
    course_gen_goal_placeholder: "Indiquez ce que vous souhaitez maîtriser...",
    course_gen_difficulty_label: "Niveau de difficulté",
    course_gen_diff_beginner: "Débutant",
    course_gen_diff_intermediate: "Intermédiaire",
    course_gen_diff_advanced: "Avancé",
    course_gen_sources_label: "Sources du Savoir",
    course_gen_select_all: "Tout sélectionner",
    course_gen_deselect_all: "Tout désélectionner",
    course_gen_no_docs: "Aucun document indexé disponible",
    course_gen_go_index: "Aller indexer des documents",
    course_gen_rag_hint: "L'IA utilisera uniquement ces documents pour générer le contenu de votre cours.",
    course_gen_generate_btn: "Générer mon Cours Personnalisé",
    course_gen_loading: "Génération du contenu pédagogique...",
    course_gen_error: "Erreur lors de la génération du cours",
    course_gen_success: "Cours généré avec succès !",
    course_gen_lesson_tab: "Leçon",
    course_gen_quiz_tab: "Quiz",
    course_gen_ready_quiz: "Prêt pour le Quiz ?",
    course_gen_back_lesson: "Retour à la leçon",
    course_gen_finish_quiz: "Terminer le Quiz",
    course_gen_next_question: "Question Suivante",
    course_gen_prev_question: "Question Précédente",
    course_gen_additional_instructions_label: "Instructions supplémentaires (optionnel)",
    course_gen_additional_instructions_placeholder: "ex: Concentrez-vous sur la pratique, incluez des exemples concrets...",
    course_gen_score_threshold: "Le seuil de réussite est de 70%.",
    course_gen_reward_btn: "Voir ma Récompense",
  },
  it: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Trasforma la documentazione interna in formazioni intelligenti",
    select_role: "Scegli il tuo profilo",
    rbac: "RBAC – Controllo degli accessi basato sui ruoli",
    admin_title: "Amministratore",
    admin_desc: "Crea formazioni, definisci le fonti, gestisci gli accessi",
    user_title: "Collaboratore",
    user_desc: "Segui le formazioni, personalizza i tuoi obiettivi, giochi di ruolo",
    invite_title: "Invita un partecipante",
    invite_desc: "Genera un link d'invito",
    invite_copy: "Copia il link",
    invite_copied: "Link copiato!",
    invite_email_placeholder: "email@esempio.com",
    invite_send: "Invia l'invito",
    enter: "Accedi",
    feat_ai: "Generazione IA",
    feat_rag: "Motore RAG",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Hosting Svizzera",
    arch_title: "Architettura Client / Server",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite eseguito nel browser dell'utente. Interfaccia di interazione con l'IA.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Ospitato da Infomaniak (Svizzera), Ubuntu Server, API sicura, motore RAG.",
    footer: "Progettato in Svizzera",
    login_title: "Accesso",
    login_email: "Indirizzo e-mail",
    login_password: "Password",
    login_submit: "Accedi",
    login_back: "Torna alla home",
    login_error: "Accesso fallito",
    login_error_desc: "Email o password errati",
    login_test_mode: "Modalità test — autenticazione locale (JSON)",
    access_restricted: "Accesso riservato ai membri",
    download: "Scarica",
    nav_dashboard: "Dashboard",
    nav_formations: "Formazioni",
    nav_documents: "Documenti",
    nav_create_course: "Generatore di Corsi",
    nav_evaluations: "Valutazioni",
    nav_roleplay: "Gioco di ruolo",
    nav_analytics: "Analytics",
    nav_users: "Utenti",
    nav_settings: "Impostazioni",
    nav_invite: "Invita",
    role_guest: "ospite",
    nav_logout: "Disconnetti",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Panoramica del Knowledge Engine",
    dashboard_subtitle_guest: "Le tue formazioni e valutazioni",
    stat_active_learners: "Studenti attivi",
    stat_active_formations: "Formazioni attive",
    stat_indexed_docs: "Documenti indicizzati",
    stat_avg_score: "Punteggio medio",
    stat_change_month: "+12% questo mese",
    stat_change_week: "+3 questa settimana",
    stat_new_docs: "82 nuovi",
    stat_vs_last_month: "+5% vs mese scorso",
    stat_assigned: "assegnate",
    formations_in_progress: "Formazioni in corso",
    active: "attive",
    modules: "moduli",
    recent_activity: "Attività recente",
    quick_generate: "Genera una formazione",
    quick_generate_desc: "Dai tuoi documenti",
    quick_analytics: "Vedi analytics",
    quick_analytics_desc: "Performance dei team",
    quick_roleplay: "Avvia un gioco di ruolo",
    quick_roleplay_desc: "Simulazione interattiva",
    quick_invite: "Invita un partecipante",
    quick_invite_desc: "Link d'invito esterno",
    docs_title: "Documenti",
    docs_subtitle: "Libreria documentale & base vettoriale",
    docs_import: "Importa",
    docs_search: "Cerca un documento...",
    docs_filter: "Filtra",
    docs_drop_zone: "Trascina i tuoi file qui o clicca per importare",
    docs_drop_subtitle: "PDF, DOCX, TXT — Max 20MB per file",
    docs_generate_training: "Genera una formazione",
    docs_generate_desc: "Descrivi la formazione da creare dai tuoi documenti importati",
    docs_chat_placeholder: "Es: Crea una formazione sulla sicurezza di rete dai documenti IT...",
    col_document: "Documento",
    col_service: "Servizio",
    col_size: "Dimensione",
    col_chunks: "Chunks",
    col_status: "Stato",
    col_date: "Data",
    col_actions: "Azioni",
    status_indexed: "Indicizzato",
    status_pending: "In corso",
    pii_anonymized: "🛡️ Dati anonimizzati",
    pii_replaced: "PII sostituite",
    formations_title: "Formazioni",
    formations_subtitle: "Percorsi generati automaticamente dall'IA",
    formations_generate: "Genera una formazione",
    formations_readonly: "Solo lettura",
    formations_admin_only: "Riservato agli admin",
    status_active: "Attiva",
    status_draft: "Bozza",
    participants: "partecipanti",
    eval_title: "Valutazioni",
    eval_next: "Successivo",
    eval_finish: "Termina",
    eval_restart: "Ricomincia",
    eval_success: "Eccellente! Hai padroneggiato questo modulo.",
    eval_fail: "Sono stati identificati degli assi di miglioramento.",
    eval_correct: "Corretto",
    eval_incorrect: "Sbagliato",
    eval_question: "Domanda",
    roleplay_title: "Gioco di ruolo",
    roleplay_subtitle: "Simulazione interattiva basata sulle tue procedure interne",
    roleplay_placeholder: "La tua azione o risposta...",
    analytics_title: "Analytics",
    analytics_subtitle: "Performance e monitoraggio delle competenze",
    analytics_completion_rate: "Tasso di completamento",
    analytics_avg_time: "Tempo medio",
    analytics_active_users: "Utenti attivi",
    analytics_global_progress: "Progresso globale",
    analytics_service_perf: "Performance per servizio",
    analytics_skills_map: "Mappa delle competenze",
    analytics_skills_desc: "Rilevamento automatico delle lacune per servizio",
    analytics_completion: "Completamento",
    analytics_avg_score: "punt. medio",
    analytics_active: "attivi",
    // AI Prompt
    nav_ai_prompt: "Prompt IA",
    ai_title: "Prompt IA",
    ai_subtitle: "Seleziona i tuoi documenti e descrivi cosa ti aspetti dall'IA",
    ai_select_docs: "Documenti disponibili",
    ai_select_all: "Seleziona tutto",
    ai_deselect_all: "Deseleziona tutto",
    ai_no_docs_yet: "Nessun documento disponibile. Importa file dalla pagina Documenti.",
    ai_clean: "Nessun PII",
    ai_prompt_label: "La tua istruzione",
    ai_prompt_placeholder: "Es: Riassumi i punti chiave di questi documenti in 5 punti...",
    ai_docs_selected: "{n} documento/i selezionato/i",
    ai_docs_none_selected: "Nessun documento selezionato",
    ai_send: "Invia",
    ai_no_docs_title: "Nessun documento",
    ai_no_docs_desc: "Seleziona almeno un documento",
    ai_no_prompt_title: "Prompt vuoto",
    ai_no_prompt_desc: "Descrivi cosa ti aspetti dall'IA",
    ai_sent_title: "Prompt inviato",
    ai_sent_desc: "La tua richiesta è stata trasmessa con i documenti selezionati",
    score: "Punteggio",
    // New keys
    person: "Persona",
    organization: "Organizzazione",
    location: "Luogo",
    misc: "Varie",
    email: "Email",
    phone: "Telefono",
    iban: "IBAN",
    social_security: "N. Previdenza",
    avs: "N. AVS",
    date: "Data",
    amount: "Importo",
    address: "Indirizzo",
    url: "URL",
    ip_address: "Indirizzo IP",
    siret_siren: "SIRET/SIREN",
    cni: "CNI",
    urssaf: "URSSAF",
    mutuelle: "Assicurazione",
    reference: "Riferimento",
    zip_code: "Codice postale",
    ide: "IDE",
    birth_date: "Data di nascita",
    cancel: "Annulla",
    confirm: "Conferma",
    close: "Chiudi",
    preview: "Anteprima",
    delete: "Elimina",
    loading: "Caricamento...",
    docs_extracting: "Estrazione del testo in corso...",
    docs_analyzed: "Documenti analizzati",
    docs_status_pii: "Stato PII",
    docs_categories: "Categorie",
    docs_date: "Data",
    docs_actions: "Azioni",
    docs_scanning_label: "Analisi...",
    docs_no_pii: "Nessun PII",
    docs_pii_count: "{n} PII",
    docs_rag_indexing: "indicizzazione RAG...",
    docs_rag_indexed: "indicizzato RAG",
    docs_rag_failed: "indicizzazione fallita",
    docs_empty_state: "Nessun documento analizzato. Importa un file per avviare il rilevamento PII.",
    docs_saving_server: "Invio al server",
    docs_saving_desc: "Trasferimento sicuro del documento in corso...",
    docs_save_success: "Analisi e trasferimento completati",
    docs_save_success_desc: "{n} dati sensibili rilevati e documento importato nel sistema RAG",
    docs_ready_for_ai: "Il documento è pronto per l'IA",
    docs_server_error: "Errore del server",
    docs_server_error_desc: "Impossibile inviare il documento al RAG.",
    docs_preview_pii_replaced: "dati sensibili sostituiti da token",
    docs_preview_no_pii: "Nessun dato sensibile rilevato",
    docs_export_tokenized: "Esporta tokenizzato",
    pii_analysis_title: "Analisi PII",
    pii_analysis_desc: "Analisi di « {name} » prima dell'invio",
    pii_verification_desc: "Verifica dei dati sensibili prima dell'elaborazione",
    pii_loading_model: "Caricamento del modello NER...",
    pii_entities_detected: "{n} dato/i sensibile/i rilevato/i",
    pii_no_entities: "Nessun dato sensibile rilevato ✓",
    pii_hide_originals: "Nascondi originali",
    pii_view_originals: "Visualizza originali",
    pii_send_anonymized: "Invia anonimizzato",
    pii_send_anyway: "Invia comunque",
    ai_generation_error: "Errore di generazione",
    ai_generation_fail_desc: "Impossibile generare una risposta.",
    ai_answer_title: "Risposta",
    ai_sources_used: "Fonti utilizzate",
    dash_current_role: "Ruolo attuale",
    dash_admin_role: "Amministratore",
    dash_user_role: "Utente",
    dash_quick_upload_desc: "Carica e analizza documenti con rilevamento PII",
    dash_system_status: "Stato del Sistema",
    dash_tool_pii: "Motore PII",
    dash_tool_rag: "Database RAG",
    dash_tool_courses: "Generatore",
    dash_status_active: "Attivo",
    dash_status_ready: "Pronto",
    dash_status_online: "Online",
    // Course Generation
    course_gen_title: "Generatore di Corsi IA",
    course_gen_subtitle: "Crea un percorso di apprendimento personalizzato dai tuoi documenti.",
    course_gen_demo_btn: "Prova la Modalità Demo",
    course_gen_setup_title: "Configurazione del Corso",
    course_gen_setup_desc: "Definisci l'argomento e i tuoi obiettivi per un'esperienza su misura.",
    course_gen_topic_label: "Argomento del corso",
    course_gen_topic_placeholder: "es: Intelligenza Artificiale, Cucina Italiana...",
    course_gen_goal_label: "Obiettivo di apprendimento",
    course_gen_goal_placeholder: "Indica cosa desideri padroneggiare...",
    course_gen_difficulty_label: "Livello di difficoltà",
    course_gen_diff_beginner: "Principiante",
    course_gen_diff_intermediate: "Intermedio",
    course_gen_diff_advanced: "Avanzato",
    course_gen_sources_label: "Fonti della Conoscenza",
    course_gen_select_all: "Seleziona tutto",
    course_gen_deselect_all: "Deseleziona tutto",
    course_gen_no_docs: "Nessun documento indicizzato disponibile",
    course_gen_go_index: "Vai a indicizzare i documenti",
    course_gen_rag_hint: "L'IA utilizzerà solo questi documenti per generare il contenuto del tuo corso.",
    course_gen_generate_btn: "Genera il mio Corso Personalizzato",
    course_gen_loading: "Generazione del contenuto pedagogico...",
    course_gen_error: "Errore durante la generazione del corso",
    course_gen_success: "Corso generato con successo!",
    course_gen_lesson_tab: "Lezione",
    course_gen_quiz_tab: "Quiz",
    course_gen_ready_quiz: "Pronto per il Quiz?",
    course_gen_back_lesson: "Torna alla lezione",
    course_gen_finish_quiz: "Termina il Quiz",
    course_gen_next_question: "Domanda Successiva",
    course_gen_prev_question: "Domanda Precedente",
    course_gen_additional_instructions_label: "Istruzioni aggiuntive (opzionale)",
    course_gen_additional_instructions_placeholder: "es: Concentrati sulla pratica, includi esempi concreti...",
    course_gen_score_threshold: "La soglia di superamento è del 70%.",
    course_gen_reward_btn: "Vedi il mio Premio",
  },
  de: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Verwandeln Sie Ihre interne Dokumentation in intelligente Schulungen",
    select_role: "Wählen Sie Ihr Profil",
    rbac: "RBAC – Rollenbasierte Zugriffskontrolle",
    admin_title: "Administrator",
    admin_desc: "Schulungen erstellen, Quellen definieren, Zugriffe verwalten",
    user_title: "Mitarbeiter",
    user_desc: "Schulungen verfolgen, Ziele personalisieren, Rollenspiele",
    invite_title: "Teilnehmer einladen",
    invite_desc: "Einladungslink generieren",
    invite_copy: "Link kopieren",
    invite_copied: "Link kopiert!",
    invite_email_placeholder: "email@beispiel.com",
    invite_send: "Einladung senden",
    enter: "Zugreifen",
    feat_ai: "KI-Generierung",
    feat_rag: "RAG-Engine",
    feat_tenant: "Multi-Tenant",
    feat_swiss: "Schweizer Hosting",
    arch_title: "Client / Server Architektur",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite im Browser des Benutzers. Interaktionsschnittstelle mit KI.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Gehostet bei Infomaniak (Schweiz), Ubuntu Server, sichere API, RAG-Engine.",
    footer: "Entwickelt in der Schweiz",
    login_title: "Anmeldung",
    login_email: "E-Mail-Adresse",
    login_password: "Passwort",
    login_submit: "Anmelden",
    login_back: "Zurück zur Startseite",
    login_error: "Anmeldung fehlgeschlagen",
    login_error_desc: "E-Mail oder Passwort falsch",
    login_test_mode: "Testmodus — lokale Authentifizierung (JSON)",
    access_restricted: "Zugang nur für Mitglieder",
    download: "Herunterladen",
    nav_dashboard: "Dashboard",
    nav_formations: "Schulungen",
    nav_documents: "Dokumente",
    nav_create_course: "Kurs-Generator",
    nav_evaluations: "Bewertungen",
    nav_roleplay: "Rollenspiel",
    nav_analytics: "Analytics",
    nav_users: "Benutzer",
    nav_settings: "Einstellungen",
    nav_invite: "Einladen",
    role_guest: "Gast",
    nav_logout: "Abmelden",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Übersicht Ihrer Knowledge Engine",
    dashboard_subtitle_guest: "Ihre Schulungen und Bewertungen",
    stat_active_learners: "Aktive Lernende",
    stat_active_formations: "Aktive Schulungen",
    stat_indexed_docs: "Indexierte Dokumente",
    stat_avg_score: "Durchschnittsnote",
    stat_change_month: "+12% diesen Monat",
    stat_change_week: "+3 diese Woche",
    stat_new_docs: "82 neue",
    stat_vs_last_month: "+5% gg. letzten Monat",
    stat_assigned: "zugewiesen",
    formations_in_progress: "Laufende Schulungen",
    active: "aktiv",
    modules: "Module",
    recent_activity: "Letzte Aktivität",
    quick_generate: "Schulung generieren",
    quick_generate_desc: "Aus Ihren Dokumenten",
    quick_analytics: "Analytics anzeigen",
    quick_analytics_desc: "Teamleistung",
    quick_roleplay: "Rollenspiel starten",
    quick_roleplay_desc: "Interaktive Simulation",
    quick_invite: "Teilnehmer einladen",
    quick_invite_desc: "Externer Einladungslink",
    docs_title: "Dokumente",
    docs_subtitle: "Dokumentenbibliothek & Vektordatenbank",
    docs_import: "Importieren",
    docs_search: "Dokument suchen...",
    docs_filter: "Filtern",
    docs_drop_zone: "Dateien hierher ziehen oder zum Importieren klicken",
    docs_drop_subtitle: "PDF, DOCX, TXT — Max 20MB pro Datei",
    docs_generate_training: "Schulung generieren",
    docs_generate_desc: "Beschreiben Sie die Schulung aus Ihren importierten Dokumenten",
    docs_chat_placeholder: "Z.B.: Eine Netzwerksicherheitsschulung aus IT-Dokumenten erstellen...",
    col_document: "Dokument",
    col_service: "Abteilung",
    col_size: "Größe",
    col_chunks: "Chunks",
    col_status: "Status",
    col_date: "Datum",
    col_actions: "Aktionen",
    status_indexed: "Indexiert",
    status_pending: "In Bearbeitung",
    pii_anonymized: "🛡️ Daten anonymisiert",
    pii_replaced: "PII ersetzt",
    formations_title: "Schulungen",
    formations_subtitle: "Automatisch von KI generierte Lernpfade",
    formations_generate: "Schulung generieren",
    formations_readonly: "Nur Lesen",
    formations_admin_only: "Nur für Admins",
    status_active: "Aktiv",
    status_draft: "Entwurf",
    participants: "Teilnehmer",
    eval_title: "Bewertungen",
    eval_next: "Weiter",
    eval_finish: "Abschließen",
    eval_restart: "Neustart",
    eval_success: "Ausgezeichnet! Sie beherrschen dieses Modul.",
    eval_fail: "Es wurden Verbesserungsbereiche identifiziert.",
    eval_correct: "Richtig",
    eval_incorrect: "Falsch",
    eval_question: "Frage",
    roleplay_title: "Rollenspiel",
    roleplay_subtitle: "Interaktive Simulation basierend auf Ihren internen Verfahren",
    roleplay_placeholder: "Ihre Aktion oder Antwort...",
    analytics_title: "Analytics",
    analytics_subtitle: "Leistung und Kompetenzmonitoring",
    analytics_completion_rate: "Abschlussrate",
    analytics_avg_time: "Durchschnittszeit",
    analytics_active_users: "Aktive Benutzer",
    analytics_global_progress: "Gesamtfortschritt",
    analytics_service_perf: "Leistung nach Abteilung",
    analytics_skills_map: "Kompetenzkarte",
    analytics_skills_desc: "Automatische Lückenerkennung nach Abteilung",
    analytics_completion: "Abschluss",
    analytics_avg_score: "Durchschn.",
    analytics_active: "aktiv",
    // AI Prompt
    nav_ai_prompt: "KI-Prompt",
    ai_title: "KI-Prompt",
    ai_subtitle: "Wählen Sie Ihre Dokumente und beschreiben Sie, was Sie von der KI erwarten",
    ai_select_docs: "Verfügbare Dokumente",
    ai_select_all: "Alle auswählen",
    ai_deselect_all: "Alle abwählen",
    ai_no_docs_yet: "Keine Dokumente verfügbar. Importieren Sie Dateien auf der Dokumente-Seite.",
    ai_clean: "Kein PII",
    ai_prompt_label: "Ihre Anweisung",
    ai_prompt_placeholder: "Z.B.: Fassen Sie die Kernpunkte dieser Dokumente in 5 Stichpunkten zusammen...",
    ai_docs_selected: "{n} Dokument(e) ausgewählt",
    ai_docs_none_selected: "Keine Dokumente ausgewählt",
    ai_send: "Senden",
    ai_no_docs_title: "Kein Dokument",
    ai_no_docs_desc: "Bitte wählen Sie mindestens ein Dokument aus",
    ai_no_prompt_title: "Prompt leer",
    ai_no_prompt_desc: "Bitte beschreiben Sie, was Sie von der KI erwarten",
    ai_sent_title: "Prompt gesendet",
    ai_sent_desc: "Ihre Anfrage wurde mit den ausgewählten Dokumenten übermittelt",
    score: "Punktzahl",
    // New keys
    person: "Person",
    organization: "Organisation",
    location: "Ort",
    misc: "Verschiedenes",
    email: "E-Mail",
    phone: "Telefon",
    iban: "IBAN",
    social_security: "Sozialversicherungsnr.",
    avs: "AVS-Nr.",
    date: "Datum",
    amount: "Betrag",
    address: "Adresse",
    url: "URL",
    ip_address: "IP-Adresse",
    siret_siren: "SIRET/SIREN",
    cni: "Personalausweis",
    urssaf: "URSSAF",
    mutuelle: "Versicherung",
    reference: "Referenz",
    zip_code: "Postleitzahl",
    ide: "IDE",
    birth_date: "Geburtsdatum",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    close: "Schließen",
    preview: "Vorschau",
    delete: "Löschen",
    loading: "Laden...",
    docs_extracting: "Extrahiere Text...",
    docs_analyzed: "Analysierte Dokumente",
    docs_status_pii: "PII-Status",
    docs_categories: "Kategorien",
    docs_date: "Datum",
    docs_actions: "Aktionen",
    docs_scanning_label: "Scanning...",
    docs_no_pii: "Kein PII gefunden",
    docs_pii_count: "{n} PII gefunden",
    docs_rag_indexing: "RAG-Indexierung...",
    docs_rag_indexed: "RAG indexiert",
    docs_rag_failed: "Indexierung fehlgeschlagen",
    docs_empty_state: "Keine Dokumente analysiert. Importieren Sie eine Datei, um die PII-Erkennung zu starten.",
    docs_saving_server: "Sende an Server",
    docs_saving_desc: "Dokument wird sicher übertragen...",
    docs_save_success: "Analyse und Übertragung abgeschlossen",
    docs_save_success_desc: "{n} sensible Daten erkannt und Dokument in das RAG-System importiert",
    docs_ready_for_ai: "Das Dokument ist bereit für die KI",
    docs_server_error: "Server-Fehler",
    docs_server_error_desc: "Das Dokument konnte nicht an RAG gesendet werden.",
    docs_preview_pii_replaced: "sensible Daten durch Token ersetzt",
    docs_preview_no_pii: "Keine sensiblen Daten erkannt",
    docs_export_tokenized: "Tokenisiert exportieren",
    pii_analysis_title: "PII-Analyse",
    pii_analysis_desc: "Analysiere '{name}' vor dem Senden",
    pii_verification_desc: "Überprüfung sensibler Daten vor der Verarbeitung",
    pii_loading_model: "Lade NER-Modell...",
    pii_entities_detected: "{n} sensible Daten erkannt",
    pii_no_entities: "Keine sensiblen Daten erkannt ✓",
    pii_hide_originals: "Originale ausblenden",
    pii_view_originals: "Originale anzeigen",
    pii_send_anonymized: "Anonymisiert senden",
    pii_send_anyway: "Trotzdem senden",
    ai_generation_error: "Generierungsfehler",
    ai_generation_fail_desc: "Eine Antwort konnte nicht generiert werden.",
    ai_answer_title: "Antwort",
    ai_sources_used: "Verwendete Quellen",
    dash_current_role: "Aktuelle Rolle",
    dash_admin_role: "Administrator",
    dash_user_role: "Benutzer",
    dash_quick_upload_desc: "Dokumente hochladen und analysieren mit PII-Erkennung",
    dash_system_status: "Systemstatus",
    dash_tool_pii: "PII-Engine",
    dash_tool_rag: "RAG-Basis",
    dash_tool_courses: "Generator",
    dash_status_active: "Aktiv",
    dash_status_ready: "Bereit",
    dash_status_online: "Online",
    // Course Generation
    course_gen_title: "KI-Kurs-Generator",
    course_gen_subtitle: "Erstellen Sie einen personalisierten Lernpfad aus Ihren Dokumenten.",
    course_gen_demo_btn: "Demo-Modus ausprobieren",
    course_gen_setup_title: "Kurs-Konfiguration",
    course_gen_setup_desc: "Definieren Sie das Thema und Ihre Ziele für ein maßgeschneidertes Erlebnis.",
    course_gen_topic_label: "Kursthema",
    course_gen_topic_placeholder: "z.B.: Künstliche Intelligenz, Italienische Küche...",
    course_gen_goal_label: "Lernziel",
    course_gen_goal_placeholder: "Geben Sie an, was Sie beherrschen möchten...",
    course_gen_difficulty_label: "Schwierigkeitsgrad",
    course_gen_diff_beginner: "Anfänger",
    course_gen_diff_intermediate: "Mittel",
    course_gen_diff_advanced: "Fortgeschritten",
    course_gen_sources_label: "Wissensquellen",
    course_gen_select_all: "Alle auswählen",
    course_gen_deselect_all: "Alle abwählen",
    course_gen_no_docs: "Keine indexierten Dokumente verfügbar",
    course_gen_go_index: "Dokumente indexieren gehen",
    course_gen_rag_hint: "Die KI verwendet nur diese Dokumente, um Ihren Kursinhalt zu generieren.",
    course_gen_generate_btn: "Meinen personalisierten Kurs generieren",
    course_gen_loading: "Pädagogischer Inhalt wird generiert...",
    course_gen_error: "Fehler bei der Kursgenerierung",
    course_gen_success: "Kurs erfolgreich generiert!",
    course_gen_lesson_tab: "Lektion",
    course_gen_quiz_tab: "Quiz",
    course_gen_ready_quiz: "Bereit für das Quiz?",
    course_gen_back_lesson: "Zurück zur Lektion",
    course_gen_finish_quiz: "Quiz beenden",
    course_gen_next_question: "Nächste Frage",
    course_gen_prev_question: "Vorherige Frage",
    course_gen_score_threshold: "Die Bestehensgrenze liegt bei 70%.",
    course_gen_reward_btn: "Meinen Preis sehen",
    course_gen_additional_instructions_label: "Zusätzliche Anweisungen (optional)",
    course_gen_additional_instructions_placeholder: "z.B. Fokus auf die Praxis, konkrete Beispiele einbeziehen...",
  },
  en: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Transform your internal documentation into intelligent training",
    select_role: "Choose your profile",
    rbac: "RBAC – Role-Based Access Control",
    admin_title: "Administrator",
    admin_desc: "Create training, define sources, manage access",
    user_title: "Collaborator",
    user_desc: "Follow your training, customize your goals, roleplay",
    invite_title: "Invite a participant",
    invite_desc: "Generate an invitation link",
    invite_copy: "Copy link",
    invite_copied: "Link copied!",
    invite_email_placeholder: "email@example.com",
    invite_send: "Send invitation",
    enter: "Enter",
    feat_ai: "AI Generation",
    feat_rag: "RAG Engine",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Swiss Hosting",
    arch_title: "Client / Server Architecture",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite running in the user's browser. AI interaction interface.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Hosted by Infomaniak (Switzerland), Ubuntu Server, secure API, RAG engine.",
    footer: "Made in Switzerland",
    login_title: "Login",
    login_email: "Email address",
    login_password: "Password",
    login_submit: "Sign in",
    login_back: "Back to home",
    login_error: "Login failed",
    login_error_desc: "Incorrect email or password",
    login_test_mode: "Test mode — local authentication (JSON)",
    access_restricted: "Access restricted to members",
    download: "Download",
    nav_dashboard: "Dashboard",
    nav_formations: "Training",
    nav_documents: "Documents",
    nav_create_course: "Course Generator",
    nav_evaluations: "Assessments",
    nav_roleplay: "Roleplay",
    nav_analytics: "Analytics",
    nav_users: "Users",
    nav_settings: "Settings",
    nav_invite: "Invite",
    role_guest: "guest",
    nav_logout: "Log out",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Overview of your Knowledge Engine",
    dashboard_subtitle_guest: "Your training and assessments",
    stat_active_learners: "Active learners",
    stat_active_formations: "Active training",
    stat_indexed_docs: "Indexed documents",
    stat_avg_score: "Average score",
    stat_change_month: "+12% this month",
    stat_change_week: "+3 this week",
    stat_new_docs: "82 new",
    stat_vs_last_month: "+5% vs last month",
    stat_assigned: "assigned",
    formations_in_progress: "Training in progress",
    active: "active",
    modules: "modules",
    recent_activity: "Recent activity",
    quick_generate: "Generate training",
    quick_generate_desc: "From your documents",
    quick_analytics: "View analytics",
    quick_analytics_desc: "Team performance",
    quick_roleplay: "Start roleplay",
    quick_roleplay_desc: "Interactive simulation",
    quick_invite: "Invite a participant",
    quick_invite_desc: "External invitation link",
    docs_title: "Documents",
    docs_subtitle: "Document library & vector database",
    docs_import: "Import",
    docs_search: "Search a document...",
    docs_filter: "Filter",
    docs_drop_zone: "Drag your files here or click to import",
    docs_drop_subtitle: "PDF, DOCX, TXT — Max 20MB per file",
    docs_generate_training: "Generate training",
    docs_generate_desc: "Describe the training to create from your imported documents",
    docs_chat_placeholder: "E.g.: Create a network security training from IT documents...",
    col_document: "Document",
    col_service: "Service",
    col_size: "Size",
    col_chunks: "Chunks",
    col_status: "Status",
    col_date: "Date",
    col_actions: "Actions",
    status_indexed: "Indexed",
    status_pending: "Pending",
    pii_anonymized: "🛡️ Data anonymized",
    pii_replaced: "PII replaced",
    formations_title: "Training",
    formations_subtitle: "AI-generated learning paths",
    formations_generate: "Generate training",
    formations_readonly: "Read only",
    formations_admin_only: "Admin only",
    status_active: "Active",
    status_draft: "Draft",
    participants: "participants",
    eval_title: "Assessments",
    eval_next: "Next",
    eval_finish: "Finish",
    eval_restart: "Restart",
    eval_success: "Excellent! You've mastered this module.",
    eval_fail: "Areas for improvement have been identified.",
    eval_correct: "Correct",
    eval_incorrect: "Incorrect",
    eval_question: "Question",
    roleplay_title: "Roleplay",
    roleplay_subtitle: "Interactive simulation based on your internal procedures",
    roleplay_placeholder: "Your action or response...",
    analytics_title: "Analytics",
    analytics_subtitle: "Performance and skills monitoring",
    analytics_completion_rate: "Completion rate",
    analytics_avg_time: "Average time",
    analytics_active_users: "Active users",
    analytics_global_progress: "Global progress",
    analytics_service_perf: "Performance by service",
    analytics_skills_map: "Skills map",
    analytics_skills_desc: "Automatic gap detection by service",
    analytics_completion: "Completion",
    analytics_avg_score: "avg. score",
    analytics_active: "active",
    // AI Prompt
    nav_ai_prompt: "AI Prompt",
    ai_title: "AI Prompt",
    ai_subtitle: "Select your documents and describe what you expect from the AI",
    ai_select_docs: "Available documents",
    ai_select_all: "Select all",
    ai_deselect_all: "Deselect all",
    ai_no_docs_yet: "No documents available. Import files from the Documents page.",
    ai_clean: "No PII",
    ai_prompt_label: "Your instruction",
    ai_prompt_placeholder: "E.g.: Summarize the key points of these documents in 5 bullet points...",
    ai_docs_selected: "{n} document(s) selected",
    ai_docs_none_selected: "No documents selected",
    ai_send: "Send",
    ai_no_docs_title: "No document",
    ai_no_docs_desc: "Please select at least one document",
    ai_no_prompt_title: "Empty prompt",
    ai_no_prompt_desc: "Please describe what you expect from the AI",
    ai_sent_title: "Prompt sent",
    ai_sent_desc: "Your request has been sent with the selected documents",
    score: "Score",
    // New keys
    person: "Person",
    organization: "Organization",
    location: "Location",
    misc: "Miscellaneous",
    email: "Email",
    phone: "Phone",
    iban: "IBAN",
    social_security: "Social Security No.",
    avs: "AVS No.",
    date: "Date",
    amount: "Amount",
    address: "Address",
    url: "URL",
    ip_address: "IP Address",
    siret_siren: "SIRET/SIREN",
    cni: "CNI",
    urssaf: "URSSAF",
    mutuelle: "Insurance",
    reference: "Reference",
    zip_code: "Zip code",
    ide: "IDE",
    birth_date: "Birth date",
    cancel: "Cancel",
    confirm: "Confirm",
    close: "Close",
    preview: "Preview",
    delete: "Delete",
    loading: "Loading...",
    docs_extracting: "Extracting text...",
    docs_analyzed: "Analyzed documents",
    docs_status_pii: "PII Status",
    docs_categories: "Categories",
    docs_date: "Date",
    docs_actions: "Actions",
    docs_scanning_label: "Scanning...",
    docs_no_pii: "No PII found",
    docs_pii_count: "{n} PII found",
    docs_rag_indexing: "RAG indexing...",
    docs_rag_indexed: "RAG indexed",
    docs_rag_failed: "indexing failed",
    docs_empty_state: "No documents analyzed. Import a file to start PII detection.",
    docs_saving_server: "Sending to server",
    docs_saving_desc: "Securely transferring the document...",
    docs_save_success: "Analysis and transfer complete",
    docs_save_success_desc: "{n} sensitive data detected and document imported to RAG system",
    docs_ready_for_ai: "The document is ready for AI",
    docs_server_error: "Server error",
    docs_server_error_desc: "The document could not be sent to RAG.",
    docs_preview_pii_replaced: "sensitive data replaced by tokens",
    docs_preview_no_pii: "No sensitive data detected",
    docs_export_tokenized: "Export tokenized",
    pii_analysis_title: "PII Analysis",
    pii_analysis_desc: "Analyzing '{name}' before sending",
    pii_verification_desc: "Verifying sensitive data before processing",
    pii_loading_model: "Loading NER model...",
    pii_entities_detected: "{n} sensitive data detected",
    pii_no_entities: "No sensitive data detected ✓",
    pii_hide_originals: "Hide originals",
    pii_view_originals: "View originals",
    pii_send_anonymized: "Send anonymized",
    pii_send_anyway: "Send anyway",
    ai_generation_error: "Generation error",
    ai_generation_fail_desc: "Unable to generate a response.",
    ai_answer_title: "Answer",
    ai_sources_used: "Sources used",
    dash_current_role: "Current role",
    dash_admin_role: "Administrator",
    dash_user_role: "User",
    dash_quick_upload_desc: "Upload and analyze documents with PII detection",
    dash_system_status: "System Status",
    dash_tool_pii: "PII Engine",
    dash_tool_rag: "RAG Base",
    dash_tool_courses: "Generator",
    dash_status_active: "Active",
    dash_status_ready: "Ready",
    dash_status_online: "Online",
    // Course Generation
    course_gen_title: "AI Course Generator",
    course_gen_subtitle: "Create a personalized learning journey from your documents.",
    course_gen_demo_btn: "Try Demo Mode",
    course_gen_setup_title: "Course Setup",
    course_gen_setup_desc: "Define the topic and your goals for a tailored experience.",
    course_gen_topic_label: "Course Topic",
    course_gen_topic_placeholder: "e.g., Artificial Intelligence, Italian Cooking...",
    course_gen_goal_label: "Learning Goal",
    course_gen_goal_placeholder: "Indicate what you want to master...",
    course_gen_difficulty_label: "Difficulty Level",
    course_gen_diff_beginner: "Beginner",
    course_gen_diff_intermediate: "Intermediate",
    course_gen_diff_advanced: "Advanced",
    course_gen_sources_label: "Knowledge Sources",
    course_gen_select_all: "Select All",
    course_gen_deselect_all: "Deselect All",
    course_gen_no_docs: "No indexed documents available",
    course_gen_go_index: "Go index documents",
    course_gen_rag_hint: "The AI will exclusively use these documents to generate your course content.",
    course_gen_generate_btn: "Generate my Personalized Course",
    course_gen_loading: "Generating pedagogical content...",
    course_gen_error: "Error during course generation",
    course_gen_success: "Course generated successfully!",
    course_gen_lesson_tab: "Lesson",
    course_gen_quiz_tab: "Quiz",
    course_gen_ready_quiz: "Ready for the Quiz?",
    course_gen_back_lesson: "Back to lesson",
    course_gen_finish_quiz: "Finish Quiz",
    course_gen_next_question: "Next Question",
    course_gen_prev_question: "Previous Question",
    course_gen_additional_instructions_label: "Additional Instructions (optional)",
    course_gen_additional_instructions_placeholder: "e.g. Focus on practice, include concrete examples...",
    course_gen_score_threshold: "The passing threshold is 70%.",
    course_gen_reward_btn: "See my Reward",
  },
  rm: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Transfurmai vossa documentaziun interna en furmaziuns intelligentas",
    select_role: "Tschernai voss profil",
    rbac: "RBAC – Controlla d'access basada sin rols",
    admin_title: "Administratur",
    admin_desc: "Creai furmaziuns, definai las funtaunas, administrai ils access",
    user_title: "Collavuratur",
    user_desc: "Suandai vossas furmaziuns, persunalisai voss finamiras, gieus da rols",
    invite_title: "Invitar in participant",
    invite_desc: "Generar ina colliaziun d'invitaziun",
    invite_copy: "Copiar la colliaziun",
    invite_copied: "Colliaziun copiada!",
    invite_email_placeholder: "email@exempel.com",
    invite_send: "Trametter l'invitaziun",
    enter: "Entrar",
    feat_ai: "Generaziun IA",
    feat_rag: "Motor RAG",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Hosting Svizzer",
    arch_title: "Architectura Client / Server",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite exequì en il navigatur da l'utilisader. Interfatscha d'interacziun cun l'IA.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Ospità tar Infomaniak (Svizra), Ubuntu Server, API segira, motor RAG.",
    footer: "Creà en Svizra",
    login_title: "Annunzia",
    login_email: "Adressa d'e-mail",
    login_password: "Pled-clav",
    login_submit: "S'annunziar",
    login_back: "Enavos a la pagina principala",
    login_error: "Annunzia fallida",
    login_error_desc: "E-mail u pled-clav incorrect",
    login_test_mode: "Modus da test — autentificaziun locala (JSON)",
    access_restricted: "Access reservà als commembers",
    download: "Telechargiar",
    nav_dashboard: "Survista",
    nav_formations: "Furmaziuns",
    nav_documents: "Documents",
    nav_create_course: "Generatur da Cuors",
    nav_evaluations: "Evaluaziuns",
    nav_roleplay: "Gieu da rols",
    nav_analytics: "Analytics",
    nav_users: "Utilisaders",
    nav_settings: "Parameters",
    nav_invite: "Invitar",
    role_guest: "ospita",
    nav_logout: "Deconnectar",
    dashboard_title: "Survista",
    dashboard_subtitle: "Survista da voss Knowledge Engine",
    dashboard_subtitle_guest: "Vossas furmaziuns ed evaluaziuns",
    stat_active_learners: "Emprendiders activs",
    stat_active_formations: "Furmaziuns activas",
    stat_indexed_docs: "Documents indexads",
    stat_avg_score: "Punct. mesaun",
    stat_change_month: "+12% quest mais",
    stat_change_week: "+3 questa emna",
    stat_new_docs: "82 novs",
    stat_vs_last_month: "+5% vs mais passà",
    stat_assigned: "attribuidas",
    formations_in_progress: "Furmaziuns en cours",
    active: "activas",
    modules: "moduls",
    recent_activity: "Activitad recenta",
    quick_generate: "Generar ina furmaziun",
    quick_generate_desc: "Da voss documents",
    quick_analytics: "Mussar analytics",
    quick_analytics_desc: "Prestaziuns da las equipas",
    quick_roleplay: "Lantschar in gieu da rols",
    quick_roleplay_desc: "Simulaziun interactiva",
    quick_invite: "Invitar in participant",
    quick_invite_desc: "Colliaziun d'invitaziun externa",
    docs_title: "Documents",
    docs_subtitle: "Biblioteca da documents & basa vectoriala",
    docs_import: "Importar",
    docs_search: "Tschertgar in document...",
    docs_filter: "Filtrar",
    docs_drop_zone: "Trai voss documents qua u cliccar per importar",
    docs_drop_subtitle: "PDF, DOCX, TXT — Max 20MB per document",
    docs_generate_training: "Generar ina furmaziun",
    docs_generate_desc: "Descrivai la furmaziun da crear da voss documents importads",
    docs_chat_placeholder: "P.ex.: Crear ina furmaziun da segirezza da rait dals documents IT...",
    col_document: "Document",
    col_service: "Servetsch",
    col_size: "Grondezza",
    col_chunks: "Chunks",
    col_status: "Status",
    col_date: "Data",
    col_actions: "Acziuns",
    status_indexed: "Indexà",
    status_pending: "En lavur",
    pii_anonymized: "🛡️ Datas anonimisadas",
    pii_replaced: "PII remplazzadas",
    formations_title: "Furmaziuns",
    formations_subtitle: "Percurs generads automaticamain da l'IA",
    formations_generate: "Generar ina furmaziun",
    formations_readonly: "Mo leger",
    formations_admin_only: "Reservà als admins",
    status_active: "Activa",
    status_draft: "Sboz",
    participants: "participants",
    eval_title: "Evaluaziuns",
    eval_next: "Proxim",
    eval_finish: "Terminar",
    eval_restart: "Recumenzar",
    eval_success: "Excellent! Vus duminais quest modul.",
    eval_fail: "Axas da meglieraziun èn vegnidas identifitgadas.",
    eval_correct: "Correct",
    eval_incorrect: "Incorrect",
    eval_question: "Dumonda",
    roleplay_title: "Gieu da rols",
    roleplay_subtitle: "Simulaziun interactiva basada sin vossas proceduras internas",
    roleplay_placeholder: "Vossa acziun u resposta...",
    analytics_title: "Analytics",
    analytics_subtitle: "Prestaziun e monitoring da las cumpetenzas",
    analytics_completion_rate: "Quota da cumplettaziun",
    analytics_avg_time: "Temp mesaun",
    analytics_active_users: "Utilisaders activs",
    analytics_global_progress: "Progress global",
    analytics_service_perf: "Prestaziun per servetsch",
    analytics_skills_map: "Carta da las cumpetenzas",
    analytics_skills_desc: "Detecziun automatica da las lacunas per servetsch",
    analytics_completion: "Cumplettaziun",
    analytics_avg_score: "punct. mes.",
    analytics_active: "activs",
    // AI Prompt
    nav_ai_prompt: "Prompt IA",
    ai_title: "Prompt IA",
    ai_subtitle: "Tschernai voss documents e descrivai tge vus spetgais da l'IA",
    ai_select_docs: "Documents disponibels",
    ai_select_all: "Tscherner tut",
    ai_deselect_all: "Destscherner tut",
    ai_no_docs_yet: "Nagins documents disponibels. Importai datotecas da la pagina Documents.",
    ai_clean: "Nagin PII",
    ai_prompt_label: "Vossa instrucziun",
    ai_prompt_placeholder: "P.ex.: Resumai ils puncts centrals da quests documents en 5 puncts...",
    ai_docs_selected: "{n} document(s) tschernì(s)",
    ai_docs_none_selected: "Nagin document tschernì",
    ai_send: "Trametter",
    ai_no_docs_title: "Nagin document",
    ai_no_docs_desc: "Tschernai almain in document",
    ai_no_prompt_title: "Prompt vid",
    ai_no_prompt_desc: "Descrivai tge vus spetgais da l'IA",
    ai_sent_title: "Prompt tramess",
    ai_sent_desc: "Vossa dumonda è vegnida transmessa cun ils documents tschernids",
    score: "Punctaziun",
    // New keys
    person: "Persuna",
    organization: "Organisaziun",
    location: "Lieu",
    misc: "Variabel",
    email: "Email",
    phone: "Telefon",
    iban: "IBAN",
    social_security: "Nr. Assicuranza",
    avs: "Nr. AVS",
    date: "Data",
    amount: "Import",
    address: "Adressa",
    url: "URL",
    ip_address: "Adressa IP",
    siret_siren: "SIRET/SIREN",
    cni: "ID/Passaport",
    urssaf: "URSSAF",
    mutuelle: "Assicuranza",
    reference: "Referenza",
    zip_code: "Numer postal",
    ide: "IDE",
    birth_date: "Data da naschientscha",
    cancel: "Annullar",
    confirm: "Confermar",
    close: "Serrar",
    preview: "Previsualisar",
    delete: "Stizzar",
    loading: "Chargiar...",
    docs_extracting: "Extracziun dal text en curs...",
    docs_analyzed: "Documents analisads",
    docs_status_pii: "Status PII",
    docs_categories: "Categorias",
    docs_date: "Data",
    docs_actions: "Acziuns",
    docs_scanning_label: "Analisa...",
    docs_no_pii: "Nagin PII chattà",
    docs_pii_count: "{n} PII chattà",
    docs_rag_indexing: "indexaziun RAG...",
    docs_rag_indexed: "indexà RAG",
    docs_rag_failed: "indexaziun fallida",
    docs_empty_state: "Nagin document analisà. Importai ina datoteca per lantschar la detecziun PII.",
    docs_saving_server: "Trametter al server",
    docs_saving_desc: "Transferiment segir dal document en curs...",
    docs_save_success: "Analisa e transferiment terminads",
    docs_save_success_desc: "{n} datas sensiblas identifitgadas e document importà en il sistem RAG",
    docs_ready_for_ai: "Il document è pront per l'IA",
    docs_server_error: "Errur dal server",
    docs_server_error_desc: "Il document n'ha betg pudì vegnir tramess al RAG.",
    docs_preview_pii_replaced: "datas sensiblas remplazzadas cun tokens",
    docs_preview_no_pii: "Naginas datas sensiblas chattadas",
    docs_export_tokenized: "Exportar tokenisà",
    pii_analysis_title: "Analisa PII",
    pii_analysis_desc: "Analisa da « {name} » avant il trametter",
    pii_verification_desc: "Verificaziun da las datas sensiblas avant il tractament",
    pii_loading_model: "Chargiar il model NER...",
    pii_entities_detected: "{n} datas sensiblas identifitgadas",
    pii_no_entities: "Naginas datas sensiblas identifitgadas ✓",
    pii_hide_originals: "Zuppentar ils originals",
    pii_view_originals: "Mussar ils originals",
    pii_send_anonymized: "Trametter anonimisà",
    pii_send_anyway: "Trametter tuttina",
    ai_generation_error: "Errur da generaziun",
    ai_generation_fail_desc: "Impossibel da generar ina resposta.",
    ai_answer_title: "Resposta",
    ai_sources_used: "Funtaunas utilisadas",
    dash_current_role: "Rol actual",
    dash_admin_role: "Administratur",
    dash_user_role: "Utilisader",
    dash_quick_upload_desc: "Chargiar ed analisar documents cun detecziun PII",
    dash_system_status: "Status dal Sistem",
    dash_tool_pii: "Motur PII",
    dash_tool_rag: "Basa RAG",
    dash_tool_courses: "Generatur",
    dash_status_active: "Activ",
    dash_status_ready: "Pront",
    dash_status_online: "Online",
    // Course Generation
    course_gen_title: "Generatur da Cuors IA",
    course_gen_subtitle: "Creai in percurs d'emprendissadi persunalisà da voss documents.",
    course_gen_demo_btn: "Essajar il Modus da Demo",
    course_gen_setup_title: "Configuraziun dal Cuors",
    course_gen_setup_desc: "Defini l'object ed ils finamiras per ina experienzi spezialisada.",
    course_gen_topic_label: "Object dal cuors",
    course_gen_topic_placeholder: "p.ex.: Intelligenzia Artificiala, Coschina Taliana...",
    course_gen_goal_label: "Finamira d'emprendissadi",
    course_gen_goal_placeholder: "Inditgai tge vus vulais duminar...",
    course_gen_difficulty_label: "Nivel da difficultad",
    course_gen_diff_beginner: "Cumenzant",
    course_gen_diff_intermediate: "Intermediar",
    course_gen_diff_advanced: "Avanzà",
    course_gen_sources_label: "Funtaunas dal Savair",
    course_gen_select_all: "Tschernair tut",
    course_gen_deselect_all: "Destscherner tut",
    course_gen_no_docs: "Nagin document indexà disponibel",
    course_gen_go_index: "Ir a indexar documents",
    course_gen_rag_hint: "L'IA utilisera mo quests documents per generar il cuntegn da voss cuors.",
    course_gen_generate_btn: "Generar mes Cuors Persunalisà",
    course_gen_loading: "Generaziun dal cuntegn pedagogic...",
    course_gen_error: "Errur durant la generaziun dal cuors",
    course_gen_success: "Cuors generà cun success!",
    course_gen_lesson_tab: "Lectiun",
    course_gen_quiz_tab: "Quiz",
    course_gen_ready_quiz: "Pront per il Quiz?",
    course_gen_back_lesson: "Enavos a la lectiun",
    course_gen_finish_quiz: "Terminar il Quiz",
    course_gen_next_question: "Proxima Dumonda",
    course_gen_prev_question: "Precedent Dumonda",
    course_gen_additional_instructions_label: "Instrucziuns supplementaras (opziunal)",
    course_gen_additional_instructions_placeholder: "p.ex. Focus sil practic, integrar exempels concrets...",
    course_gen_score_threshold: "Il limit da success è 70%.",
    course_gen_reward_btn: "Vair mes Premio",
  },
};

interface LanguageContextType {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocale] = useState<Locale>("fr");
  const t = (key: string) => translations[locale]?.[key] ?? key;
  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};